# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobby.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blobby.proto\"&\n\x13\x43heckVersionRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\"\'\n\x14\x43heckVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\"\'\n\x13ResourceHostRequest\x12\x10\n\x08rversion\x18\x01 \x01(\t\":\n\x14ResourceHostResponse\x12\x10\n\x08rversion\x18\x01 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lobby_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKVERSIONREQUEST._serialized_start=15
  _CHECKVERSIONREQUEST._serialized_end=53
  _CHECKVERSIONRESPONSE._serialized_start=55
  _CHECKVERSIONRESPONSE._serialized_end=94
  _RESOURCEHOSTREQUEST._serialized_start=96
  _RESOURCEHOSTREQUEST._serialized_end=135
  _RESOURCEHOSTRESPONSE._serialized_start=137
  _RESOURCEHOSTRESPONSE._serialized_end=195
# @@protoc_insertion_point(module_scope)
