# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: live_tip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elive_tip.proto\"\xb2\x02\n\x07LiveTip\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.LiveTip.LiveTipType\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\"\xcf\x01\n\x0bLiveTipType\x12\x0b\n\x07Unknown\x10\x00\x12\x10\n\x0cNotPossessed\x10\x01\x12\x15\n\x11LowActivatingRate\x10\x02\x12\x0e\n\nInCoolTime\x10\x03\x12\x13\n\x0fStaminaShortage\x10\x04\x12\x08\n\x04Miss\x10\x05\x12\x14\n\x10SkillHeavyWeight\x10\x06\x12\x14\n\x10\x41udienceShortage\x10\x07\x12\x11\n\rLevelShortage\x10\x08\x12\x11\n\rDeckUnbalance\x10\t\x12\t\n\x05Other\x10\nb\x06proto3')



_LIVETIP = DESCRIPTOR.message_types_by_name['LiveTip']
_LIVETIP_LIVETIPTYPE = _LIVETIP.enum_types_by_name['LiveTipType']
LiveTip = _reflection.GeneratedProtocolMessageType('LiveTip', (_message.Message,), {
  'DESCRIPTOR' : _LIVETIP,
  '__module__' : 'live_tip_pb2'
  # @@protoc_insertion_point(class_scope:LiveTip)
  })
_sym_db.RegisterMessage(LiveTip)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIVETIP._serialized_start=19
  _LIVETIP._serialized_end=325
  _LIVETIP_LIVETIPTYPE._serialized_start=118
  _LIVETIP_LIVETIPTYPE._serialized_end=325
# @@protoc_insertion_point(module_scope)
